# Connecting and configuring our postgres DB.

#spring:
#  datasource:
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/student
#    password: admin

spring:
  profiles:
    active: dev